### PR TITLE
Add separate files for MD5

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by Chuvi-w** [comment]
This files seems to be missed in vcxproj.

**Comment by In-line** [comment]
https://github.com/In-line/rehlds/blob/8dc893929534426e9393169da1d8872b34af3d60/rehlds/msvc/ReHLDS.vcxproj#L324

**Comment by Chuvi-w** [comment]
.h is a header only, Visual Studio doesn't include existing .cpp automatically.

**Comment by In-line** [comment]
@Chuvi-w My mistake. I can't send PR for that now. Please, do it. I use linux as Desktop OS, so was unable to test.

**Comment by Chuvi-w** [comment]
Maybe some times later. (If nobody noticed this bug, maybe, no one uses Visual Studio 0_o)

**Comment by LevShisterov** [comment]
Fixed.

**Pull request merged**
