### PR TITLE
Added replacing escape sequences in kick reason (#154)

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**
#154

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Or better add this feature to all commands?

**Comment by theAsmodai** [comment]
For what exactly commands?

**Comment by WPMGPRoSToTeMa** [comment]
@theAsmodai I think about replacing in Cmd_ExecuteString.

**Comment by theAsmodai** [comment]
No, I think it's not a good idea for incoming commands.

**Pull request merged**
