### PR TITLE
Remove useless dev mode from Host_WriteConfiguration

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by LeninChan** [comment]
if (!developer.value
 +#ifndef REHLDS_FIXES
 +		|| !FS_FileExists("../goldsrc/dev_build_all.bat"
 +#endif
 +		)

maybe?

**Comment by In-line** [comment]
I think it is code that original hlds developers forget to remove after some testing.

**Comment by theAsmodai** [comment]
It's clientside code.

**Comment by In-line** [comment]
@theAsmodai , so why don't fix it ? I think , I don't understand something. Can you explain?

**Comment by theAsmodai** [comment]
We can fix, but it makes no sense. It willn't be used.

**Pull request closed without merging**
