### PR TITLE
Implement `svc_exec` support in the engine and HLTV

### LINKED ISSUE #734: [TFC] SVC_EXEC - Message Unregistered
A new SVC_EXEC message was added to TFC to exec class specific cfg files on clients in a recent update. But since ReHLDS is based on an earlier version, class cfgs no longer auto exec at spawn. Without this, clients need to manually exec a cfg every time they switch class, which a pain in the ass.

Other than that, everything else seemed to work well and I would probably use ReHLDS if this were to be fixed.

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**
Resolves #734.

### CODE REVIEW

**Comment by LevShisterov** [comment]
Probably [net_internal.h](https://github.com/dreamstalker/rehlds/blob/65c6ce593b5eabf13e92b03352e4b429d0d797b0/rehlds/HLTV/common/net_internal.h#L162) should be changed too.

**Comment by WPMGPRoSToTeMa** [comment]
> 
> 
> Probably [net_internal.h](https://github.com/dreamstalker/rehlds/blob/65c6ce593b5eabf13e92b03352e4b429d0d797b0/rehlds/HLTV/common/net_internal.h#L162) should be changed too.

Changed it. @LevShisterov, @s1lentq please take a look at my latest changes.

**Comment by s1lentq** [comment]
it seems to be fine

**Comment by WPMGPRoSToTeMa** [comment]
@s1lentq done, note that `64` is an id of the first user message, not the last svc_*.

**Pull request merged**
