### PR TITLE
Cut of nicknames '+' if next there is something digit or alphanumeric character.

### PR DESCRIPTION
**Pull request by s1lentq**
Added prefix Q_* for functions strlen/strcmp/strpcy/memset/memcpy/memmove etc.
Added for solution configuration (Debug Swds Play/Release Swds Play) the path to libacof32.lib in linker.

### CODE REVIEW

**Comment by latinas** [comment]
I have one question: what feature in Q_ functions? They works faster or smthng else?

**Comment by s1lentq** [comment]
@latinas AFAIR Asmodai already answered your question https://github.com/dreamstalker/rehlds/pull/82#issuecomment-148952932

**Comment by latinas** [comment]
Ah, i thought this functions and functions Asmodai added in 82 commit are different. Ok, thanks for answer

**Comment by theAsmodai** [comment]
Functions with Q_ prefix is only a definitions that makes it easy to replace standart library functions.

**Comment by WPMGPRoSToTeMa** [comment]
Why do you need cut '+' characters of nicknames?

**Comment by theAsmodai** [comment]
Since this is an unused feauture causing only problems.

**Comment by WPMGPRoSToTeMa** [comment]
@theAsmodai what feature?

**Comment by theAsmodai** [comment]
I don't know useful applications of displaying buttons with binds.

**Comment by WPMGPRoSToTeMa** [comment]
@theAsmodai are you about ShowMenu message?

**Comment by theAsmodai** [comment]
Yes.

**Comment by WPMGPRoSToTeMa** [comment]
First of all ShowMenu message is a part of game, not engine. Therefore this should be fixed in game part (gamedll/clientdll), but not in engine. Secondly you can remove/replace this characters from nickname only for ShowMenu in plugins code. ('+' in scoreboard doesn't cause bugs)

**Comment by theAsmodai** [comment]
The engine contains so many dirty hacks (especially for CS). Since there is no way to fix the client, we have to do so.

**Comment by WPMGPRoSToTeMa** [comment]
@theAsmodai, but it can be fixed in gamedll.

**Comment by theAsmodai** [comment]
How? Changing some chars will lead to mismatched nicknames in different places and collision problems.

**Comment by WPMGPRoSToTeMa** [comment]
@theAsmodai you can replace '+' to U+2795 before show it in 'bugged' menu.

**Comment by theAsmodai** [comment]
It's possible if nickname doesn't take all available length. But this correction must be done in a hundred places.

**Comment by WPMGPRoSToTeMa** [comment]
@theAsmodai this is plugins problem, not engine and gamedll. Show nicknames in ShowMenu is '
undocumented feature'. Why the plugins problem should be fixed in engine?

**Comment by theAsmodai** [comment]
Be realistic. Otherwise, the problem will never be solved.

**Comment by WPMGPRoSToTeMa** [comment]
The ShowMenu problem should be fixed in ShowMenu. So you can hook ShowMenu message and replace/remove characters in it, but don't do this in nickname.

**Comment by theAsmodai** [comment]
Too complicated for such a simple thing. The '+' char in names are very rarely used.

**Pull request merged**
