### PR TITLE
Add GetEntityInit hook

### LINKED ISSUE #722: [Linux Only Issue] Hook GetEntityInit
Hello. When trying to hook the function GetEntityInit on Linux ReHLDS, the server crashes with a segmentation fault. On Windows it all works fine. Same goes if using a HLDS linux server. It's just Linux ReHLDS where it's not working fine.

I also recommend adding more hooks to ReAPI if possible, and maybe integrating this function somewhere to be hookable, as it's quite useful. For example, joropito wrote a plug-in that makes use of this function. The main purpose of it is to fix entities that are not valid in mods such as TFC, for example. Basically about making the maps compatible with custom mods.

https://forums.alliedmods.net/showthread.php?p=1647630

I also recommend that you add more hooks to ReHLDS (hookchains), such as Steam_GSBSecure to be able to determine if a server is VAC-secured or not.

Here I attach some code, the Orpheu module was used.
```
public plugin_init()
{
    g_hFuncGetEntityInit = OrpheuGetFunction("GetEntityInit");

    if(g_hFuncGetEntityInit != OrpheuInvalidFunction)
    {
        g_hGetEntityInit = OrpheuRegisterHook(g_hFuncGetEntityInit, "OnGetEntityInit", OrpheuHookPre);
    }
}

public OrpheuHookReturn: OnGetEntityInit(const szClassName[])
{
    if(equal(szClassName, g_szWorldClass) || equal(szClassName, g_szTeleClass))
    {
        OrpheuSetParam(1, g_szTargetEntName);
    }

    return OrpheuIgnored;
}

### PR DESCRIPTION
**Pull request by Amaroq7**
I got the request to add the hookchain for `GetEntityInit`, so this PR just adds it, nothing more, nothing less. 😛 

Fixes #722.

Signed-off-by: Karol Szuster <karolsz9898@gmail.com>

### CODE REVIEW

**Comment by StevenKal** [comment]
@s1lentq: You make a file adjustement the day the PR got published (so, you were quickly aware of it), but today, you still not merge it. Seriously, stop being dumb at giving false hope to the people, and learn to express yourself with words when people ask things (you look like an unfinished robot). So, close the PR if you dislike that addition because you are dumb, or merge it as soon as possible. Pff, how do you expect people try to contribute, do PRs & cie when you do not even consider them and play the dead when they ask things nicely, that's why I had no motivation to try this when I see how this goes with you.
By the way, your new downloads is kind of dumb too, on the past there were "pure" & "bugfixed", but later this has been removed for some reasons (and this was good, at least for simplicity & because the "pure" was no longer interesting, plus more for dev/test purpose of the reverse-engineering), but now I can see a "release" downloads, & a "dev" one. Well, I feel "interesting" the fact we can get the "artifacts" of the PRs not merged yet when you are lazy or unable to merge them, for the impatients ones, and this kind of files should be branded as "dev", but once mergued to the comits & approved, this should stay in "release", the "release" files should not be stopped like that. Keep the simplicity for the users.
Besides, this is more annoying to get the dev files, some people might not found the "artifacts" things.

**Comment by etojuice** [comment]
typical 'nice guy' comment LOL

**Comment by StevenKal** [comment]
Sounds like I have finally been heard. Good.

**Comment by WaLkZa** [comment]
@Amaroq7 could you add it in ReAPI?

**Pull request merged**
