### PR TITLE
fix for split packets

### PR DESCRIPTION
**Pull request by verimavcisi**
its a fix for split attack
server dont have to receive split packets but hlds can handle it
when someone spams split packets, server's buffer will be filled

open source split spammer:
https://raw.githubusercontent.com/verimavcisi/projeler/master/linux/half-life/split_spammer/split_spammer.c
compile: gcc split.spammer.c
usage: sudo ./a.out sourceip destinationip destinationport packetdelay

summary when you start split spammer:
not connectable server WITHOUT this commit
no ping difference or no any lag WITH this commit

### CODE REVIEW

**Comment by theAsmodai** [comment]
Hello. I think you don't understand how it works. This flooder sends 4-byte fffffffe header from spoofed addresses which can cause only flood to the console in developer mode. You should not use developer mode on public servers.

**Comment by theAsmodai** [comment]
Your experiment is incorrect because testing client was launched on the same machine where the flooder. I think it is the only reason why do you see lags.

**Comment by krangm** [comment]
actually i helped @verimavcisi to test that spammer on different servers im hosting.
it ealisy makes server unplayable

**Comment by justgo97** [comment]
yeah this split packet flood can make server unplayable and i guess just a cvar for turning the console message OFF/ON is enough

**Comment by verimavcisi** [comment]
theAsmodai
i tested not local rehlds servers too (with precompiled binary and my commit)

krangm
thanks for reply

justgo97
you watchted video what i recorded ?
i cant see any console message when i spam splits but server gets lag

**Comment by verimavcisi** [comment]
theAsmodai
this code only working when packet is split and packet size lower than 9
`
Con_NetPrintf("Invalid split packet length %i\n", in_message.cursize);
return FALSE;
`
net_ws.cpp NET_QueuePacket's this part just checking split packet's accuracy
"
https://i.imgur.com/3tCIfSh.png
if everything is okay for split packet call NET_GetLong function
"
problem is when you call NET_GetLong every 15625< (default 64 splits in second) micro second server's buffer will be filled
my commit returns instantly NET_QueuePacket function when packet type is split
i never see hl client send split packet for anything so split should be not exist

**Comment by verimavcisi** [comment]
@WPMGPRoSToTeMa i dont think so
if this code really blocking split packets why precompiled rehlds binary lagging ? (with my commit server dont get lags)

**Comment by WPMGPRoSToTeMa** [comment]
@verimavcisi try commenting `Con_NetPrintf` and test again.

**Comment by verimavcisi** [comment]
@WPMGPRoSToTeMa server still gets lag when i open split spammer

**Comment by WPMGPRoSToTeMa** [comment]
@verimavcisi try replacing `return FALSE;` to `return TRUE;`.

**Comment by verimavcisi** [comment]
@WPMGPRoSToTeMa tested on local and not local server, only no lag for local server, this line should be not exist maybe ? if (sock == NS_SERVER)

bye the way code going to be same thing with my pull request

**Comment by theAsmodai** [comment]
I think you enabled sv_cheats and fakelag cvars. Theay are should be 0.

**Comment by verimavcisi** [comment]
@theAsmodai man, you should try it by yourself instead of blame me with useless messages

**Comment by theAsmodai** [comment]
No, you should justify the need of suggested changes or I close this useless thread.

**Comment by Shigbeard** [comment]
Justification: Without this, my server was lagged out so hard the server's watchdog couldn't verify it was even up. With this patch made by @verimavcisi, the attack that he attempted on my server, the one I attempted on my server, and the one my other server attempted on my server, all failed to impact gameplay or even the server watchdog.

Note that in my tests, sv_cheats was disabled. There was no fakelag in use. Before implementing this patch, I was using the latest version of rehlds and the only change that occured between stock hlds and rehlds was that rehlds suppressed an error message in the server console.

The point I'm trying to make @theAsmodai is that rehlds DOES NOT currently protect against specially crafted split packet spam. This pull request implements changes to rehlds that DOES protect against specially crafted split packet spam. I've tested it first hand. @verimavcisi tested it with me. I've tried to use split packet spamming from 3 different sources: Internally from same machine as server, externally from same IP as a connected client, and externally from an IP that is neither connected to the server as a client or even on the same subnet as the client. All of these sources could virtually halt the server before installing this patch. All of these sources could not affect the server after installing this patch.

There's your justification for this pull request. 
✋ 
💨 
🎤

**Comment by theAsmodai** [comment]
> The point I'm trying to make @theAsmodai is that rehlds DOES NOT currently protect against specially crafted split packet spam.

You are wrong. **ALL** split packets already disabled without any error messages, logs, etc... I'm close this PR because anyway it's incorrect. If you disagree you can investigate rehlds sources deeper and describe founded problem in issues section. I'm waiting for something like this: https://github.com/dreamstalker/rehlds/issues/17
If the problem really exists, then we will think how to fix it.

**Comment by LevShisterov** [comment]
With Con_DPrintf there is some overwork with flight recording.

**Pull request closed without merging**
