### PR TITLE
Fix accuracy, improve bullet physics. 

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by stamepicmorg** [comment]
Самый полезный коммит, который я тут видел 💃

**Comment by voed** [comment]
> ...linux version of HLDS, engine_i486.so

ReHLDS now affecting not only engine_i486.so, so i think this remark can be removed. It will give "стрельба как в 5787".

**Comment by theAsmodai** [comment]
Impressive! You really found the problem.

**Comment by WPMGPRoSToTeMa** [comment]
:trollface:

**Comment by fred0r** [comment]
Reads nice.
Thank you so much for supporting the best FPS-Game ever !

**Comment by Phantomsq** [comment]
Omfg. Finally!

**Comment by IgnacioFDM** [comment]
We should probably increase API major version because of this.

**Comment by justgo97** [comment]
nice catch.

**Pull request merged**
