### PR TITLE
Add hitbox visualization

### PR DESCRIPTION
**Pull request by In-line**
## Added cvars

- sv_rehlds_hitboxes_draw —  0 to disable, >=0.1 to set redraw delay
- sv_rehlds_hitboxes_groups — hitgroups that should be drawn (abcdefg flags)

### Credits

- @WPMGPRoSToTeMa for initial hitbox points calculation code, suggestions
- @s1lentq for constant support, reviews, suggestions.

### TODO:

- [x] Implementation
- [ ] Wiki page about hitgroups?
- [x] Update README.md

**CAUTION!** You should enable this only for debugging purposes. Player unreliable buffer can overflow!

### CODE REVIEW

**Comment by Phantomsq** [comment]
I think all these changes must be under REHLDS_ADD macro

**Comment by Freeman-AM** [comment]
Any update regarding this PR ?
I'm sure many people in CS would love to test that. ;)

**Comment by In-line** [comment]
@Freeman-AM https://github.com/s1lentq/hitboxtracker

**Comment by Sh1ft0x0EF** [comment]
@s1lentq 
thx for the launcher code

**Comment by Dr-Strange91** [comment]
Any updates? Regarding it? Because, this issue still persists !!!

I took this video from Internet:
https://youtu.be/umEO6BDsEwM

Problem is similar !!!

**Comment by Karaulov** [comment]
Why it works on hostages and player himself ? ))

This is same as mirv_draw_sv_hitboxes_enable in advancedfx?

**Comment by RauliTop** [comment]
Can this be merged?

Will be great to testing purposes.

**Comment by wopox1337** [comment]
At the moment, the engine has restrictions on how customers can display the "lines" ([beams](https://github.com/dreamstalker/rehlds/pull/490/files#diff-2ecc605ae13bffe82b41e64dd69f8a58c7d6e3db55df05a11528a1c14507f71aR667-R696) `sprites/laserbeam.spr`) with which these hitboxes are drawn. 

The number of displays is very limited. For this reason, only one of the groups of hitboxes (or several, but not all at once) can be displayed.

It would be a very strange decision to accept the functionality in such a way. 
image


In addition, even when displaying a single hitbox group, there are some problems. 

It is probably better NOT to display "own" hitbox.
image



PR updated to the current version of the engine from the master branch. 
- Download actual build with added this functionality is possible [from CI artifacts](https://github.com/dreamstalker/rehlds/actions/runs/2176827112).

Closed, until problems are resolved.

**Pull request closed without merging**
