### PR TITLE
Add MAX_CVARLIST_FILES define

### PR DESCRIPTION
**Pull request by In-line**

### CODE REVIEW

**Comment by LevShisterov** [comment]
No need for REHLDS_FIXES and value checks.

**Comment by In-line** [comment]
@LevShisterov Here will be problem if value is above 100 https://github.com/In-line/rehlds/blob/bd8019da9f01308ef57f957b8614e127bed137f8/rehlds/engine/cvar.cpp#L595

**Comment by In-line** [comment]
@LevShisterov Fixed. My mistake.

**Comment by LevShisterov** [comment]
No problem. Thanks.

**Pull request merged**
