### PR TITLE
SV_ParseResourceList more readable: reduce REHLDS_FIXES count and remove unused code.

### PR DESCRIPTION
**Pull request by 2020karaulov2020**
SV_ParseResourceList more readable: reduce REHLDS_FIXES count and remove unused code.

### CODE REVIEW

**Comment by s1lentq** [comment]
This optimization at code level is nonsense, because compiler perfectly understands `total <1` and as a consequence will be unroll loop, look in IDA to make sure.
IMO, this PR it will only worsen the readability of the code.

**Comment by 2020karaulov2020** [comment]
@s1lentq okay I rename these pull request)

**Comment by 2020karaulov2020** [comment]
@s1lentq 5 REHLDS_FIXES into 1 REHLDS_FIXES. lol.

**Comment by s1lentq** [comment]
> @s1lentq 5 REHLDS_FIXES into 1 REHLDS_FIXES 😄

I meant that manually unroll loop it worse

**Comment by 2020karaulov2020** [comment]
> > @s1lentq 5 REHLDS_FIXES into 1 REHLDS_FIXES 😄
> 
> I meant that manually unroll loop it worse

I just tried to remove many unnecessary REHLDS_FIXES, and save only one. Loop unnecessary, because it not readable in these case. You can do it as needed ))

**Comment by 2020karaulov2020** [comment]
@s1lentq okay I close it ( You can add in ReGamedll : https://dev-cs.ru/threads/16067/#post-107985 ?? )

**Pull request closed without merging**
