### PR TITLE
Fix Issue #377

### PR DESCRIPTION
**Pull request by Sh1ft0x0EF**
[WARNING] This PR requires C++14 so I've modified the `rehlds/build.gradle` file to support it

### CODE REVIEW

**Comment by Sh1ft0x0EF** [comment]
> Execution failed for task ':rehlds:unitTestReleaseRehldsFixesRehlds_swds_engineSharedLibrary'. org.gradle.api.GradleException: Unable to fetch test names

???

**Comment by Sh1ft0x0EF** [comment]
Windows failed to build with:
> Unable to fetch test names

**Comment by In-line** [comment]
It was already discussed in #377. Besides this PR can't be merged, cause `std::unique_ptr` requires newer libstdc++ library then in HLDS root.

**Comment by Sh1ft0x0EF** [comment]
Remove dependency of C++14, 11 will be enough now

**Comment by Sh1ft0x0EF** [comment]
TeamCity has finally built it...
Buildable now!

**Comment by Sh1ft0x0EF** [comment]
#512 broke the build for this PR

**Comment by s1lentq** [comment]
1. https://github.com/dreamstalker/rehlds/issues/377#issuecomment-316067253
2. https://github.com/dreamstalker/rehlds/pull/504#issuecomment-317687663

This PR can't be reopen until the project is linked to libstdc++ statically ¯ \ _ (ツ) _ / ¯

**Pull request closed without merging**
