### PR TITLE
Fixed optimization-dependent model bounds computation in R_GetStudioB…

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**
…ounds (actually in R_StudioCalcBonePosition) (related to #239)

Tested only under windows, anybody please test it under linux.

### CODE REVIEW

**Comment by LevShisterov** [comment]
What the purpose of using volatile variables?

**Comment by WPMGPRoSToTeMa** [comment]
> What the purpose of using volatile variables?

That was the first idea how to fix this (suggested by @theAsmodai)

Now I understand that the problem was in `short` to `float` casts.

**Comment by IgnacioFDM** [comment]
I don't understand. The original code should always return the same value regardless of any optimization as far as I understand. How are you testing this?

**Comment by theAsmodai** [comment]
The problem is caused by different floating point calculation precision with different optimization settings.

**Comment by WPMGPRoSToTeMa** [comment]
@IgnacioFDM read #239 to reproduce. In original code `mstudioanimvalue_t::value` can be casted to `float` or `long double`. With `SSE2` in `MSVC` it will cast it to `float`, therefore all calculations will produce `float`. Client code of this function has `long double` cast, `long double` is more accurate than `float`. Thats why client bounds calculations not equal to server bounds calculations.

**Comment by WPMGPRoSToTeMa** [comment]
As I can see via dissasembler the linux engine is fine too.

**Pull request merged**
