### PR TITLE
Allowed spectator and global unreliable buffer to overflow

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**
Extended spectator buffer

### CODE REVIEW

**Comment by souvikdas95** [comment]
What are the causes and effects of this?

**Comment by WPMGPRoSToTeMa** [comment]
It isn't investigated fully, but gamedll sometimes can send a lot of message for `hltv` from player's `TakeDamage`. (when `TakeDamage` is called a lot of times in the same frame) It is good to extend `hltv` buffer to max datagram size to prevent overflows. And 'hltv' buffer was allowed to overflow because engine already has code that tells: `hltv` buffer can overflow, see https://github.com/dreamstalker/rehlds/blob/fb3ec088e1238237fd23b9005309dbb297c8a5c5/rehlds/engine/sv_main.cpp#L4789-L4793
But this not actually solves the problem, there is should be an investigation how to prevent this flood in gamedll (can these messages be combined in one for the same frame?).

**Comment by souvikdas95** [comment]
Is it only related to HLTV and not players?

**Comment by WPMGPRoSToTeMa** [comment]
@souvikdas95 `spectator` buffer is only for HLTV, but it crashes server when overflow.

**Comment by souvikdas95** [comment]
seems to have fixed by crashes though not related to hlds since i have particularly blocked hltv clients from entering the server.

**Comment by WPMGPRoSToTeMa** [comment]
It will crash even without HLTV.

**Pull request merged**
